//
//  DevelopmentPreview.swift
//  SwiftUI-TravelApp
//
//  Created by Malyadri Reddy on 07/03/25.
//

import Foundation

class DevelopmentPreview {
    
    static let shared = DevelopmentPreview()
    
    var listings: [Listing] = [
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "Malyadri",
              ownerImageUri: "male-profile-photo",
              numberofbedRooms: 4,
              numberofBathRooms: "3",
              numberofGuests: "4",
              numberofBeds: "4",
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              address: "124 main st",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckin, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
              listingType: .villa,
              imageUrls: ["t1","t2","t3","t4"]),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "Jhon",
                  ownerImageUri: "male-profile-photo",
                  numberofbedRooms: 4,
                  numberofBathRooms: "3",
                  numberofGuests: "4",
                  numberofBeds: "4",
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  address: "124 main st",
                  city: "Nellore",
                  state: "Florida",
                  title: "Miami Town",
                  rating: 4.86,
                  features: [.selfCheckin, .superHost],
                  amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
                  listingType: .villa,
                  imageUrls: ["t2","t1","t3","t5"]),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "Ronaldo",
                  ownerImageUri: "male-profile-photo",
                  numberofbedRooms: 4,
                  numberofBathRooms: "3",
                  numberofGuests: "4",
                  numberofBeds: "4",
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  address: "124 main st",
                  city: "Nellore",
                  state: "Florida",
                  title: "Miami Balcony",
                  rating: 4.86,
                  features: [.selfCheckin, .superHost],
                  amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
                  listingType: .villa,
                  imageUrls: ["t5","t1","t3","t2"]),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "Henry",
                  ownerImageUri: "male-profile-photo",
                  numberofbedRooms: 4,
                  numberofBathRooms: "3",
                  numberofGuests: "4",
                  numberofBeds: "4",
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  address: "124 main st",
                  city: "Nellore",
                  state: "Florida",
                  title: "Miami Suite",
                  rating: 4.86,
                  features: [.selfCheckin, .superHost],
                  amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
                  listingType: .villa,
                  imageUrls: ["t3","t1","t4","t5"]),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "Cook",
                  ownerImageUri: "male-profile-photo",
                  numberofbedRooms: 4,
                  numberofBathRooms: "3",
                  numberofGuests: "4",
                  numberofBeds: "4",
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  address: "124 main st",
                  city: "Vinjamuru",
                  state: "Florida",
                  title: "Miami vilage",
                  rating: 4.86,
                  features: [.selfCheckin, .superHost],
                  amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv],
                  listingType: .villa,
                  imageUrls: ["t4","t1","t2","t3"])
        
    ]
}
